before_install:
  - echo | sudo apt-add-repository ppa:dhart/ppa
  - echo | sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get remove -y cmake
  - sudo apt-get -qq update
  - sudo apt-get install -y cxxtest cmake

env: CXXTEST=/usr/include

script:
  - ./build.sh

compiler:
  - gcc

language: cpp
