before_install:
  - echo | sudo apt-add-repository ppa:dhart/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y cxxtest

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

env: CXXTEST=/usr/include

script:
  - ./build.sh

compiler:
  - gcc

language: cpp
